services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server"]

  publisher:
    build:
      context: ./publisher
    container_name: publisher
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis

  subscriber:
    build:
      context: ./subscriber
    deploy:
      replicas: 2
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
